name: ON PUSH
on:
  push:
    branches:
      - feature/**
jobs:
  on_push_to_feature:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: create output
        id: list_outputs
        outputs:
          jira_ticket_numer: ${{ steps.jira_ticket.outputs.jira_ticket_numer }}
          feature_branch_name: $(echo ${GITHUB_REF#refs/heads/})
          preprod_branch_name: ${{ steps.create_preprod_branch.outputs.preprod_branch_name }}
      - name: Get Jira Ticket
        id: jira_ticket
        run: |
          branch_name=$(echo ${GITHUB_REF#refs/heads/})
          JIRA_TICKET_NUMBER=$(echo $branch_name | awk -F"/" '{print $2}')
          echo "::set-output name=jira_ticket_numer::$JIRA_TICKET_NUMBER"
      - name: create preprod branch
        id: create_preprod_branch
        run : |
          RELEASE_BRANCH_NAME="preprod/{{ list_outputs.outputs.jira_ticket_numer }}"
          echo "::set-output name=preprod_branch_name::$RELEASE_BRANCH_NAME"
          echo "Checking $RELEASE_BRANCH_NAME existing or not"
          if [ $(git ls-remote --heads origin $RELEASE_BRANCH_NAME|wc -l) == 0 ];
            then
                echo "The release branch $RELEASE_BRANCH_NAME does not exists in remote. Hence creating the new branch from master"
                git checkout -b $RELEASE_BRANCH_NAME
                git push origin $RELEASE_BRANCH_NAME
                echo "The new branch has been created. Please raise PR against this branch to merge changes to Pre-Prod"
          fi
      - name: Create draft PR for Preprod
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: {{ list_outputs.outputs.feature_branch_name }}
          target_branch: {{ list_outputs.outputs.preprod_branch_name }}
          title: Release {{ list_outputs.outputs.jira_ticket_numer }} to pre-production
          template: .github/PULL_REQUEST_TEMPLATE.md
          draft: true
          get_diff: true
  publish_release_from_main:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - name: Create draft release
        id: create_draft_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_draft_release.outputs.id }}
