name: PR
on:
  pull_request:
    branches:
      - release/**
      - Release/**
      - RELEASE/**
      - main
jobs:
  pr_on_release_branch:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release')
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check naming convention of source
        run : |
          src_branch_name=${GITHUB_HEAD_REF}
          if [ $(echo $src_branch_name | grep -c 'feature/') != 1 ];
            then
              echo "Looks like the branch name does not follow naming convention standard as source to merge into release branch \n"
              echo "Hence aborting this check. Please close this PR and either create new branch or rename existing new branch and raise new PR\n"
              echo "Please follow naming standard of feature/<jira_ticket_number>"
              exit 1
          fi
      - name: validate source and destination
        run : |
          src_branch_name=${GITHUB_HEAD_REF}
          tgt_branch_name=${GITHUB_BASE_REF}

          src_jira_ticket_num=$(echo $src_branch_name | awk -F"/" '{print $2}')
          expected_tgt_branch_name="release/$src_jira_ticket_num"

          if [ $expected_tgt_branch_name != $tgt_branch_name ];
            then
              echo "It looks the expected target is not correct. Please close this PR and raise another PR with correct target"
              exit 1
          fi
  pr_on_main_branch:
    runs-on: ubuntu-latest
    if: contains(github.base_ref, 'main')
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: validate source branch
        run : |
          src_branch_name=${GITHUB_HEAD_REF}
          if [ $(echo $src_branch_name | grep -c 'release/') != 1 ];
            then
              echo "Looks like you are trying a PR from branch other than release/.This action is blocked\n"
              echo "Hence failing this check. Please close this PR"
              echo "Please select appropriate release branch which should look like this release/**"
              exit 1
          fi
