name: PR
on:
  - pull_request
jobs:
  check_commit_in_develop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: branch name
        run: |
          echo ${{ github.ref }}