name: PR
on:
  push:
    branches:
      - feature/**
jobs:
  check_commit_in_develop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create release branch
        run : |
          echo "Creating the release branch from the feature branch $GITHUB_HEAD_REF"
          JIRA_TICKET_NUMBER=`echo ${GITHUB_HEAD_REF}|awk -F"/" '{print $2}'`
          RELEASE_BRANCH_NAME='release/${JIRA_TICKET_NUMBER}'
          echo "Checking if the release branch ${RELEASE_BRANCH_NAME} already exists in remote"
          if [ (`git ls-remote --heads origin ${RELEASE_BRANCH_NAME}|wc -l`) == 1 ];
            then
                echo "Branch already exist in remote. Do nothing"
                exit 0
            else
                echo "The release branch $RELEASE_BRANCH_NAME does not exists in remote. Hence creating the new branch from master"
                git checkout origin/main
                git branch -b $RELEASE_BRANCH_NAME
                git push origin $RELEASE_BRANCH_NAME
                echo "The new branch has been created. Please raise PR against this branch to merge changes to Pre-Prod"
          fi
