name: PR
on:
  pull_request:
    branches:
        - main
jobs:
  check_commit_in_develop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: source branch name
        run: |
          echo ${GITHUB_HEAD_REF}
      - name: desitination branch name
        run: |
          echo ${GITHUB_BASE_REF}
      - name: Hash commit
        run: |
          echo ${GITHUB_SHA}
      - name: Check if Hash commit in develop branch
        run: |
          if [ ${GITHUB_BASE_REF} == 'develop' ];
            then
                echo "This is a develop branch. exiting the check"
                exit 0
          elif [ 0 -eq $(git branch --contains $GITHUB_SHA|grep -c develop) ];
             then
                 echo "${GITHUB_SHA} not found in develop. Aborting the merge"
                 echo "Please commit the change to develop branch and wait for UAT completion before you merge the changes to master branch"
                 exit 1
          fi
