name: PR
on:
  - pull_request
jobs:
  check_commit_in_develop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: source branch name
        run: |
          echo ${GITHUB_HEAD_REF}
      - name: desitination branch name
        run: |
          echo ${GITHUB_BASE_REF}